name: Plugin Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Apache
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo a2enmod rewrite
        sudo service apache2 start

    - name: Setup MySQL
      run: |
        sudo apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE wordpress;"
        sudo mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'wordpress';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Setup PHP
      run: |
        sudo apt-get install -y php php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip

    - name: Setup WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Configure Apache Virtual Host
      run: |
        sudo tee /etc/apache2/sites-available/wordpress.conf << EOF
        <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/wordpress
            <Directory /var/www/wordpress>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
            </Directory>
            ErrorLog \${APACHE_LOG_DIR}/error.log
            CustomLog \${APACHE_LOG_DIR}/access.log combined
        </VirtualHost>
        EOF
        sudo a2ensite wordpress.conf
        sudo a2dissite 000-default.conf
        sudo service apache2 restart

    - name: Install WordPress
      run: |
        sudo mkdir -p /var/www/wordpress
        sudo chown -R www-data:www-data /var/www/wordpress
        cd /var/www/wordpress
        sudo -u www-data wp core download
        sudo -u www-data wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=localhost
        sudo -u www-data wp core install --url=localhost --title="WordPress Test" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email

    - name: Install Plugin Check Plugin    
      run: |
        cd /var/www/wordpress/wp-content/plugins/
        sudo -u www-data wp plugin install plugin-check --activate
        
    - name: Install Plugin
      run: |
        sudo cp -r . /var/www/wordpress/wp-content/plugins/wp-learn-sensei-content/
        sudo chown -R www-data:www-data /var/www/wordpress/wp-content/plugins/wp-learn-sensei-content/
        sudo -u www-data wp plugin activate wp-learn-sensei-content
