name: Plugin Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Server
      run: |
        sudo apt update
        sudo apt upgrade -y

    - name: Setup PHP with SQLite
      run: |
        sudo apt-get install -y php php-sqlite3 php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip

    - name: Setup WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Install WordPress with SQLite
      run: |
        sudo mkdir -p /var/www/wordpress
        sudo chown -R $USER /var/www/wordpress
        cd /var/www/wordpress
        wp core download --allow-root
        # Create wp-config.php with SQLite configuration
        wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=localhost --skip-check --allow-root
        # Add SQLite configuration to wp-config.php
        sed -i "/define( 'DB_NAME', 'wordpress' );/a define( 'DB_TYPE', 'sqlite' );" wp-config.php
        wp core install --url=localhost --title="WordPress Test" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email --allow-root
        # Download SQLite integration plugin
        wp plugin install sqlite-integration --activate --allow-root
        
    - name: Install Plugin Check Plugin    
      run: |
        cd /var/www/wordpress/wp-content/plugins/
        wp plugin install plugin-check --activate --allow-root        
